version: '3.8'

services:

  app:
    build: .
    env_file:
      - .env
    environment:
      db_dsn: "postgresql://postgres:password@db:5433/postgres"
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    hostname: db
    expose:
      - "5433" # Publishes 5431 to other containers but NOT to host machine
    ports:
      - "5433:5433"  # unwanted conflict with database in main pc
    command: -p 5433
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
    build:
      shm_size: '4gb'
